// Generates selfhost/.env with fresh secrets: Postgres password, JWT secret,
// and the anon / service_role API keys (HS256 JWTs signed with that secret,
// 10-year expiry — same shape the Supabase platform issues).
//
// Usage: node scripts/generate-secrets.mjs [--force]
// Refuses to overwrite an existing .env without --force (rotating JWT_SECRET
// invalidates every session and both API keys; the frontend build and the CI
// variables must be updated to match).

import { randomBytes, createHmac } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const envPath = join(dirname(fileURLToPath(import.meta.url)), '..', '.env');
if (existsSync(envPath) && !process.argv.includes('--force')) {
  console.error(`${envPath} already exists. Re-run with --force to rotate ALL secrets.`);
  process.exit(1);
}

const alnum = (n) => randomBytes(n * 2).toString('base64url').replace(/[-_]/g, '').slice(0, n);
const b64u = (buf) => Buffer.from(buf).toString('base64url');

function signHS256(payload, secret) {
  const header = b64u(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = b64u(JSON.stringify(payload));
  const sig = createHmac('sha256', secret).update(`${header}.${body}`).digest('base64url');
  return `${header}.${body}.${sig}`;
}

const now = Math.floor(Date.now() / 1000);
const tenYears = 10 * 365 * 24 * 3600;

const JWT_SECRET = randomBytes(32).toString('hex');
const keyFor = (role) => signHS256({ role, iss: 'supabase', iat: now, exp: now + tenYears }, JWT_SECRET);

const env = `# Generated by scripts/generate-secrets.mjs on ${new Date().toISOString()}
# NEVER commit this file. See .env.example for the field reference.

############ Secrets ############
POSTGRES_PASSWORD=${alnum(32)}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${keyFor('anon')}
SERVICE_ROLE_KEY=${keyFor('service_role')}

# Studio dashboard (http://127.0.0.1:8000, basic auth)
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${alnum(24)}

SECRET_KEY_BASE=${randomBytes(48).toString('base64')}
REALTIME_DB_ENC_KEY=${randomBytes(8).toString('hex')}
VAULT_ENC_KEY=${randomBytes(16).toString('hex')}
PG_META_CRYPTO_KEY=${alnum(32)}

# Opaque/asymmetric keys unused - legacy HS256 mode.
SUPABASE_PUBLISHABLE_KEY=
SUPABASE_SECRET_KEY=
ANON_KEY_ASYMMETRIC=
SERVICE_ROLE_KEY_ASYMMETRIC=

############ URLs ############
# Public URL of this backend (Caddy fronts kong on this hostname).
SUPABASE_PUBLIC_URL=https://games-api.kh3dron.net
API_EXTERNAL_URL=https://games-api.kh3dron.net/auth/v1

# Frontend origin for auth redirects/emails.
SITE_URL=https://games.kh3dron.net
ADDITIONAL_REDIRECT_URLS=https://games.kh3dron.net/**,http://localhost:5173/**,http://localhost:4173/**

############ Database ############
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

############ Auth ############
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
# No SMTP configured: signups auto-confirm (no verification email) and magic
# links FAIL until SMTP_* below are filled in with a real provider.
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

SMTP_ADMIN_EMAIL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=topologic-go

MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

############ Edge Functions ############
# Functions enforce auth themselves (requireUser); router-level check off.
FUNCTIONS_VERIFY_JWT=false

############ PostgREST ############
PGRST_DB_SCHEMAS=public,graphql_public
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public

############ Kong / Studio ############
KONG_HTTP_PORT=8000
STUDIO_DEFAULT_ORGANIZATION=topologic-go
STUDIO_DEFAULT_PROJECT=topologic-go
`;

writeFileSync(envPath, env, { mode: 0o600 });
console.log(`wrote ${envPath}`);
console.log(`ANON_KEY=${keyFor('anon').slice(0, 40)}... (full value in .env)`);
